from __future__ import annotations

class RegisterKind:
    Holding: RegisterKind
    Input: RegisterKind

class ModbusPoint:
    def kind(self) -> RegisterKind: ...
    def register(self) -> int: ...
    def scale(self) -> float: ...
    def offset(self) -> float: ...

class ModbusTcpSource:
    def __init__(self, host_port: str) -> None: ...

def parse_modbus_address(s: str) -> ModbusPoint: ...
def map_register(raw: int, point: ModbusPoint) -> float: ...
