from __future__ import annotations

from . import engine as engine

class FlowsheetId:
    def __init__(self, raw: str) -> None: ...
    def as_str(self) -> str: ...
    def __str__(self) -> str: ...

class UnitOpId:
    def __init__(self, raw: str) -> None: ...
    def as_str(self) -> str: ...
    def __str__(self) -> str: ...

class StreamId:
    def __init__(self, raw: str) -> None: ...
    def as_str(self) -> str: ...
    def __str__(self) -> str: ...

class ScenarioId:
    def __init__(self, raw: str) -> None: ...
    def as_str(self) -> str: ...
    def __str__(self) -> str: ...

class UnitOpKind:
    Mixer: UnitOpKind
    Splitter: UnitOpKind
    Heater: UnitOpKind
    Cooler: UnitOpKind
    Valve: UnitOpKind
    Pump: UnitOpKind
    FlashDrum: UnitOpKind
    Pipe: UnitOpKind

class ThermoPackage:
    PengRobinson: ThermoPackage
    Srk: ThermoPackage
    PcSaft: ThermoPackage
    IdealGas: ThermoPackage

class EngineCapability:
    SteadyState: EngineCapability
    Dynamic: EngineCapability

class FlowsheetState:
    Draft: FlowsheetState
    Approved: FlowsheetState

class ChemicalComponent:
    def __init__(self, name: str) -> None: ...
    def name(self) -> str: ...

class Composition:
    def __init__(self, fractions: list[float]) -> None: ...
    def fractions(self) -> list[float]: ...
    def sum(self) -> float: ...
    def len(self) -> int: ...
    def is_empty(self) -> bool: ...

class UnitOp:
    def __init__(self, id: UnitOpId, kind: UnitOpKind, name: str) -> None: ...
    def id(self) -> UnitOpId: ...
    def kind(self) -> UnitOpKind: ...
    def name(self) -> str: ...

class MaterialStream:
    # Also accepts keyword-only argument `from: UnitOpId | None`.
    def __init__(
        self,
        id: StreamId,
        composition: Composition,
        *,
        to: UnitOpId | None = None,
    ) -> None: ...
    def id(self) -> StreamId: ...
    def from_(self) -> UnitOpId | None: ...
    def to(self) -> UnitOpId | None: ...
    def composition(self) -> Composition: ...
    def is_feed(self) -> bool: ...
    def is_product(self) -> bool: ...

class Specification:
    def __init__(self, unit_op: UnitOpId, variable: str, value: float) -> None: ...
    def unit_op(self) -> UnitOpId: ...
    def variable(self) -> str: ...
    def value(self) -> float: ...

class BoundaryCondition:
    def __init__(self, variable: str, value: float) -> None: ...
    def variable(self) -> str: ...
    def value(self) -> float: ...

class FlowsheetSpec:
    @staticmethod
    def draft(
        id: FlowsheetId,
        *,
        components: list[ChemicalComponent],
        unit_ops: list[UnitOp],
        streams: list[MaterialStream],
        specs: list[Specification],
        thermo: ThermoPackage,
    ) -> FlowsheetSpec: ...
    def id(self) -> FlowsheetId: ...
    def version(self) -> int: ...
    def state(self) -> FlowsheetState: ...
    def is_approved(self) -> bool: ...
    def degrees_of_freedom(self) -> int: ...
    def thermo(self) -> ThermoPackage: ...
    def approve(self) -> None: ...

class Scenario:
    @staticmethod
    def approve(
        id: ScenarioId,
        flowsheet: FlowsheetSpec,
        *,
        boundary_conditions: list[BoundaryCondition],
        duration_secs: float,
        required_capability: EngineCapability,
    ) -> Scenario: ...
    def id(self) -> ScenarioId: ...
    def flowsheet(self) -> FlowsheetId: ...
    def flowsheet_version(self) -> int: ...
    def boundary_conditions(self) -> list[BoundaryCondition]: ...
    def duration_secs(self) -> float: ...
    def required_capability(self) -> EngineCapability: ...
    def is_approved(self) -> bool: ...
