from __future__ import annotations

from .simulation import Scenario

class StreamState:
    def __init__(
        self,
        mass_flow: float,
        pressure: float,
        temperature: float,
        composition: list[float],
    ) -> None: ...
    def mass_flow(self) -> float: ...
    def pressure(self) -> float: ...
    def temperature(self) -> float: ...
    def composition(self) -> list[float]: ...

class FirstOrderEngine:
    def __init__(self, tau_secs: float) -> None: ...
    def initialize(self, scenario: Scenario) -> None: ...
    def step(self, dt_secs: float) -> list[tuple[str, float]]: ...
    def current_time(self) -> float: ...
    def value_of(self, variable: str) -> float | None: ...

def mix(inlets: list[StreamState]) -> StreamState: ...
def split(inlet: StreamState, fractions: list[float]) -> list[StreamState]: ...
def valve(inlet: StreamState, outlet_pressure: float) -> StreamState: ...
def pump(
    inlet: StreamState,
    *,
    outlet_pressure: float,
    density: float,
    efficiency: float,
) -> tuple[StreamState, float]: ...
def pipe(inlet: StreamState, delta_p: float) -> StreamState: ...
