# DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/python/mod.rs
# Based on "crates/store/re_sdk_types/definitions/rerun/blueprint/datatypes/filter_by_range.fbs".

# You can extend this class by creating a "FilterByRangeExt" class in "filter_by_range_ext.py".

from __future__ import annotations

from collections.abc import Sequence
from typing import Any

import pyarrow as pa
from attrs import define, field

from ... import datatypes
from ..._baseclasses import (
    BaseBatch,
)

__all__ = ["FilterByRange", "FilterByRangeArrayLike", "FilterByRangeBatch", "FilterByRangeLike"]


def _filter_by_range__start__special_field_converter_override(x: datatypes.TimeIntLike) -> datatypes.TimeInt:
    if isinstance(x, datatypes.TimeInt):
        return x
    else:
        return datatypes.TimeInt(x)


def _filter_by_range__end__special_field_converter_override(x: datatypes.TimeIntLike) -> datatypes.TimeInt:
    if isinstance(x, datatypes.TimeInt):
        return x
    else:
        return datatypes.TimeInt(x)


@define(init=False)
class FilterByRange:
    """
    **Datatype**: Configuration for the filter-by-range feature of the dataframe view.

    ⚠️ **This type is _unstable_ and may change significantly in a way that the data won't be backwards compatible.**
    """

    def __init__(self: Any, start: datatypes.TimeIntLike, end: datatypes.TimeIntLike) -> None:
        """
        Create a new instance of the FilterByRange datatype.

        Parameters
        ----------
        start:
            Beginning of the time range.
        end:
            End of the time range (inclusive).

        """

        # You can define your own __init__ function as a member of FilterByRangeExt in filter_by_range_ext.py
        self.__attrs_init__(start=start, end=end)

    start: datatypes.TimeInt = field(converter=_filter_by_range__start__special_field_converter_override)
    # Beginning of the time range.
    #
    # (Docstring intentionally commented out to hide this field from the docs)

    end: datatypes.TimeInt = field(converter=_filter_by_range__end__special_field_converter_override)
    # End of the time range (inclusive).
    #
    # (Docstring intentionally commented out to hide this field from the docs)


FilterByRangeLike = FilterByRange
"""A type alias for any FilterByRange-like object."""

FilterByRangeArrayLike = FilterByRange | Sequence[FilterByRangeLike]
"""A type alias for any FilterByRange-like array object."""


class FilterByRangeBatch(BaseBatch[FilterByRangeArrayLike]):
    _ARROW_DATATYPE = pa.struct([
        pa.field("start", pa.int64(), nullable=False, metadata={}),
        pa.field("end", pa.int64(), nullable=False, metadata={}),
    ])

    @staticmethod
    def _native_to_pa_array(data: FilterByRangeArrayLike, data_type: pa.DataType) -> pa.Array:
        from rerun.datatypes import TimeIntBatch

        typed_data: Sequence[FilterByRange]

        if isinstance(data, FilterByRange):
            typed_data = [data]
        else:
            typed_data = data

        return pa.StructArray.from_arrays(
            [
                TimeIntBatch([x.start for x in typed_data]).as_arrow_array(),  # type: ignore[misc, arg-type]
                TimeIntBatch([x.end for x in typed_data]).as_arrow_array(),  # type: ignore[misc, arg-type]
            ],
            fields=list(data_type),
        )
