from __future__ import annotations

from ..kernel import Measurement, TagId, TimeWindow

class TagSeries:
    def tag(self) -> TagId: ...
    def measurements(self) -> list[Measurement]: ...

class QueryResult:
    def series(self) -> list[TagSeries]: ...

class RrdDataframeQuery:
    @staticmethod
    def open(path: str) -> RrdDataframeQuery: ...
    def query(self, window: TimeWindow, tags: list[TagId]) -> QueryResult: ...
