# DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/python/mod.rs
# Based on "crates/store/re_sdk_types/definitions/rerun/datatypes/class_description.fbs".

# You can extend this class by creating a "ClassDescriptionExt" class in "class_description_ext.py".

from __future__ import annotations

from collections.abc import Sequence
from typing import TYPE_CHECKING, Any

import pyarrow as pa
from attrs import define, field

from .._baseclasses import (
    BaseBatch,
)

__all__ = ["ClassDescription", "ClassDescriptionArrayLike", "ClassDescriptionBatch", "ClassDescriptionLike"]


@define(init=False)
class ClassDescription:
    """
    **Datatype**: The description of a semantic Class.

    If an entity is annotated with a corresponding [`components.ClassId`][rerun.components.ClassId], Rerun will use
    the attached [`datatypes.AnnotationInfo`][rerun.datatypes.AnnotationInfo] to derive labels and colors.

    Keypoints within an annotation class can similarly be annotated with a
    [`components.KeypointId`][rerun.components.KeypointId] in which case we should defer to the label and color for the
    [`datatypes.AnnotationInfo`][rerun.datatypes.AnnotationInfo] specifically associated with the Keypoint.

    Keypoints within the class can also be decorated with skeletal edges.
    Keypoint-connections are pairs of [`components.KeypointId`][rerun.components.KeypointId]s. If an edge is
    defined, and both keypoints exist within the instance of the class, then the
    keypoints should be connected with an edge. The edge should be labeled and
    colored as described by the class's [`datatypes.AnnotationInfo`][rerun.datatypes.AnnotationInfo].

    Note that a `ClassDescription` can be directly logged using `rerun.log`.
    This is equivalent to logging a `rerun.AnnotationContext` containing
    a single `ClassDescription`.
    """

    def __init__(
        self: Any,
        *,
        info: datatypes.AnnotationInfoLike,
        keypoint_annotations: datatypes.AnnotationInfoArrayLike,
        keypoint_connections: datatypes.KeypointPairArrayLike,
    ) -> None:
        """
        Create a new instance of the ClassDescription datatype.

        Parameters
        ----------
        info:
            The [`datatypes.AnnotationInfo`][rerun.datatypes.AnnotationInfo] for the class.
        keypoint_annotations:
            The [`datatypes.AnnotationInfo`][rerun.datatypes.AnnotationInfo] for all of the keypoints.
        keypoint_connections:
            The connections between keypoints.

        """

        # You can define your own __init__ function as a member of ClassDescriptionExt in class_description_ext.py
        self.__attrs_init__(
            info=info, keypoint_annotations=keypoint_annotations, keypoint_connections=keypoint_connections
        )

    info: datatypes.AnnotationInfo = field()
    # The [`datatypes.AnnotationInfo`][rerun.datatypes.AnnotationInfo] for the class.
    #
    # (Docstring intentionally commented out to hide this field from the docs)

    keypoint_annotations: list[datatypes.AnnotationInfo] = field()
    # The [`datatypes.AnnotationInfo`][rerun.datatypes.AnnotationInfo] for all of the keypoints.
    #
    # (Docstring intentionally commented out to hide this field from the docs)

    keypoint_connections: list[datatypes.KeypointPair] = field()
    # The connections between keypoints.
    #
    # (Docstring intentionally commented out to hide this field from the docs)


if TYPE_CHECKING:
    from .. import datatypes

    ClassDescriptionLike = ClassDescription | datatypes.AnnotationInfoLike
    """A type alias for any ClassDescription-like object."""
else:
    ClassDescriptionLike = Any

ClassDescriptionArrayLike = ClassDescription | Sequence[ClassDescriptionLike]
"""A type alias for any ClassDescription-like array object."""


class ClassDescriptionBatch(BaseBatch[ClassDescriptionArrayLike]):
    _ARROW_DATATYPE = pa.struct([
        pa.field(
            "info",
            pa.struct([
                pa.field("id", pa.uint16(), nullable=False, metadata={}),
                pa.field("label", pa.utf8(), nullable=True, metadata={}),
                pa.field("color", pa.uint32(), nullable=True, metadata={}),
            ]),
            nullable=False,
            metadata={},
        ),
        pa.field(
            "keypoint_annotations",
            pa.list_(
                pa.field(
                    "item",
                    pa.struct([
                        pa.field("id", pa.uint16(), nullable=False, metadata={}),
                        pa.field("label", pa.utf8(), nullable=True, metadata={}),
                        pa.field("color", pa.uint32(), nullable=True, metadata={}),
                    ]),
                    nullable=False,
                    metadata={},
                )
            ),
            nullable=False,
            metadata={},
        ),
        pa.field(
            "keypoint_connections",
            pa.list_(
                pa.field(
                    "item",
                    pa.struct([
                        pa.field("keypoint0", pa.uint16(), nullable=False, metadata={}),
                        pa.field("keypoint1", pa.uint16(), nullable=False, metadata={}),
                    ]),
                    nullable=False,
                    metadata={},
                )
            ),
            nullable=False,
            metadata={},
        ),
    ])

    @staticmethod
    def _native_to_pa_array(data: ClassDescriptionArrayLike, data_type: pa.DataType) -> pa.Array:
        raise NotImplementedError(
            "Arrow serialization of ClassDescription not implemented: We lack codegen for arrow-serialization of general structs"
        )  # You need to implement native_to_pa_array_override in class_description_ext.py
