# DO NOT EDIT! This file was auto-generated by crates/build/re_types_builder/src/codegen/python/mod.rs
# Based on "crates/store/re_sdk_types/definitions/rerun/datatypes/tensor_dimension_selection.fbs".

# You can extend this class by creating a "TensorDimensionSelectionExt" class in "tensor_dimension_selection_ext.py".

from __future__ import annotations

from collections.abc import Sequence
from typing import TYPE_CHECKING, Any

import numpy as np
import numpy.typing as npt
import pyarrow as pa
from attrs import define, field

from .._baseclasses import (
    BaseBatch,
)

__all__ = [
    "TensorDimensionSelection",
    "TensorDimensionSelectionArrayLike",
    "TensorDimensionSelectionBatch",
    "TensorDimensionSelectionLike",
]


@define(init=False)
class TensorDimensionSelection:
    """**Datatype**: Selection of a single tensor dimension."""

    def __init__(self: Any, dimension: int, invert: bool) -> None:
        """
        Create a new instance of the TensorDimensionSelection datatype.

        Parameters
        ----------
        dimension:
            The dimension number to select.
        invert:
            Invert the direction of the dimension.

        """

        # You can define your own __init__ function as a member of TensorDimensionSelectionExt in tensor_dimension_selection_ext.py
        self.__attrs_init__(dimension=dimension, invert=invert)

    dimension: int = field(converter=int)
    # The dimension number to select.
    #
    # (Docstring intentionally commented out to hide this field from the docs)

    invert: bool = field(converter=bool)
    # Invert the direction of the dimension.
    #
    # (Docstring intentionally commented out to hide this field from the docs)


if TYPE_CHECKING:
    TensorDimensionSelectionLike = TensorDimensionSelection | int
    """A type alias for any TensorDimensionSelection-like object."""
else:
    TensorDimensionSelectionLike = Any

TensorDimensionSelectionArrayLike = TensorDimensionSelection | Sequence[TensorDimensionSelectionLike] | npt.ArrayLike
"""A type alias for any TensorDimensionSelection-like array object."""


class TensorDimensionSelectionBatch(BaseBatch[TensorDimensionSelectionArrayLike]):
    _ARROW_DATATYPE = pa.struct([
        pa.field("dimension", pa.uint32(), nullable=False, metadata={}),
        pa.field("invert", pa.bool_(), nullable=False, metadata={}),
    ])

    @staticmethod
    def _native_to_pa_array(data: TensorDimensionSelectionArrayLike, data_type: pa.DataType) -> pa.Array:

        typed_data: Sequence[TensorDimensionSelection]

        if isinstance(data, TensorDimensionSelection):
            typed_data = [data]
        else:
            typed_data = data

        return pa.StructArray.from_arrays(
            [
                pa.array(np.asarray([x.dimension for x in typed_data], dtype=np.uint32)),
                pa.array(np.asarray([x.invert for x in typed_data], dtype=np.bool_)),
            ],
            fields=list(data_type),
        )
