from __future__ import annotations

from .kernel import AlarmLimits, EngineeringRange, TagId, UnitOfMeasure

class FacilityId:
    def __init__(self, raw: str) -> None: ...
    def as_str(self) -> str: ...
    def __str__(self) -> str: ...

class AreaId:
    def __init__(self, raw: str) -> None: ...
    def as_str(self) -> str: ...
    def __str__(self) -> str: ...

class UnitId:
    def __init__(self, raw: str) -> None: ...
    def as_str(self) -> str: ...
    def __str__(self) -> str: ...

class EquipmentId:
    def __init__(self, raw: str) -> None: ...
    def as_str(self) -> str: ...
    def __str__(self) -> str: ...

class EquipmentKind:
    Vessel: EquipmentKind
    Tank: EquipmentKind
    Pump: EquipmentKind
    HeatExchanger: EquipmentKind
    Valve: EquipmentKind
    Pipe: EquipmentKind
    Other: EquipmentKind

class ProcessUnit:
    def id(self) -> UnitId: ...
    def name(self) -> str: ...

class Area:
    def id(self) -> AreaId: ...
    def name(self) -> str: ...
    def units(self) -> list[ProcessUnit]: ...

class Facility:
    @staticmethod
    def define(id: FacilityId, name: str) -> Facility: ...
    def id(self) -> FacilityId: ...
    def name(self) -> str: ...
    def areas(self) -> list[Area]: ...
    def has_area(self, area: AreaId) -> bool: ...
    def has_unit(self, unit: UnitId) -> bool: ...
    def add_area(self, id: AreaId, name: str) -> None: ...
    def add_unit(self, area: AreaId, unit: UnitId, name: str) -> None: ...

class Equipment:
    def id(self) -> EquipmentId: ...
    def unit(self) -> UnitId: ...
    def name(self) -> str: ...
    def kind(self) -> EquipmentKind: ...

class Tag:
    def id(self) -> TagId: ...
    def equipment(self) -> EquipmentId: ...
    def description(self) -> str: ...
    def unit(self) -> UnitOfMeasure: ...
    def range(self) -> EngineeringRange: ...
    def alarms(self) -> AlarmLimits | None: ...

class AssetCatalog:
    def facility(self) -> Facility: ...
    def equipment(self) -> list[Equipment]: ...
    def tags(self) -> list[Tag]: ...
    def tag(self, *, id: TagId) -> Tag | None: ...
    def equipment_by_id(self, *, id: EquipmentId) -> Equipment | None: ...
    def validate(self) -> None: ...

class TomlCatalogRepository:
    def __init__(self, path: str) -> None: ...
    def load_catalog(self) -> AssetCatalog: ...
