from __future__ import annotations

class Quality:
    Good: Quality
    Uncertain: Quality
    Bad: Quality
    def is_usable(self) -> bool: ...

class Dimension:
    Pressure: Dimension
    Temperature: Dimension
    VolumetricFlow: Dimension
    MassFlow: Dimension
    Length: Dimension
    Dimensionless: Dimension

class UnitOfMeasure:
    Kilopascal: UnitOfMeasure
    Bar: UnitOfMeasure
    Psi: UnitOfMeasure
    Megapascal: UnitOfMeasure
    DegreeCelsius: UnitOfMeasure
    Kelvin: UnitOfMeasure
    CubicMeterPerHour: UnitOfMeasure
    BarrelPerDay: UnitOfMeasure
    KilogramPerHour: UnitOfMeasure
    Meter: UnitOfMeasure
    Percent: UnitOfMeasure
    Ratio: UnitOfMeasure
    def dimension(self) -> Dimension: ...
    def symbol(self) -> str: ...
    def to_base(self, value: float) -> float: ...
    def from_base(self, base_value: float) -> float: ...
    def same_dimension(self, other: UnitOfMeasure) -> bool: ...

class TagId:
    def __init__(self, raw: str) -> None: ...
    def as_str(self) -> str: ...
    def __str__(self) -> str: ...

class Measurement:
    def __init__(self, value: float, quality: Quality, timestamp: float) -> None: ...
    def value(self) -> float: ...
    def quality(self) -> Quality: ...
    def timestamp(self) -> float: ...
    def timestamp_nanos(self) -> int: ...
    def timestamp_iso(self) -> str: ...
    def __str__(self) -> str: ...

class MeasurementBatch:
    def __init__(self, tag: TagId, samples: list[Measurement]) -> None: ...
    def tag(self) -> TagId: ...
    def samples(self) -> list[Measurement]: ...
    def len(self) -> int: ...
    def is_empty(self) -> bool: ...
    def time_span(self) -> TimeWindow | None: ...

class TimeWindow:
    def __init__(self, start: float, end: float) -> None: ...
    def start(self) -> float: ...
    def end(self) -> float: ...
    def start_nanos(self) -> int: ...
    def end_nanos(self) -> int: ...
    def start_iso(self) -> str: ...
    def end_iso(self) -> str: ...
    def contains(self, ts: float) -> bool: ...
    def overlaps(self, other: TimeWindow) -> bool: ...
    def duration(self) -> float: ...
    def __str__(self) -> str: ...

class EngineeringRange:
    def __init__(self, low: float, high: float, unit: UnitOfMeasure) -> None: ...
    def low(self) -> float: ...
    def high(self) -> float: ...
    def unit(self) -> UnitOfMeasure: ...
    def span(self) -> float: ...
    def contains(self, value: float) -> bool: ...

class AlarmLimits:
    def __init__(
        self,
        low_low: float | None = None,
        low: float | None = None,
        high: float | None = None,
        high_high: float | None = None,
        *,
        unit: UnitOfMeasure,
    ) -> None: ...
    def low_low(self) -> float | None: ...
    def low(self) -> float | None: ...
    def high(self) -> float | None: ...
    def high_high(self) -> float | None: ...
    def unit(self) -> UnitOfMeasure: ...
