from __future__ import annotations

from . import dataframe_query as dataframe_query
from .asset_model import AssetCatalog
from .kernel import TagId, TimeWindow

class FeatureSpec:
    def __init__(self, tag: TagId, name: str) -> None: ...
    def tag(self) -> TagId: ...
    def name(self) -> str: ...

class DataSplit:
    def __init__(
        self,
        train: TimeWindow,
        test: TimeWindow,
        *,
        val: TimeWindow | None = None,
    ) -> None: ...
    def train(self) -> TimeWindow: ...
    def val(self) -> TimeWindow | None: ...
    def test(self) -> TimeWindow: ...
    def windows(self) -> list[tuple[str, TimeWindow]]: ...

class DatasetSpec:
    @staticmethod
    def define(
        id: str,
        *,
        features: list[FeatureSpec],
        targets: list[FeatureSpec],
        split: DataSplit,
        catalog: AssetCatalog,
    ) -> DatasetSpec: ...
    def id(self) -> str: ...
    def version(self) -> int: ...
    def features(self) -> list[FeatureSpec]: ...
    def targets(self) -> list[FeatureSpec]: ...
    def split(self) -> DataSplit: ...
