from __future__ import annotations

from collections.abc import Sequence

from .asset_model import EquipmentKind

class Connector:
    @property
    def index(self) -> int: ...
    @property
    def direction_deg(self) -> int: ...
    @property
    def pos(self) -> tuple[float, float]: ...

class Symbol:
    def id(self) -> str: ...
    def kind(self) -> str: ...
    def svg(self) -> bytes: ...
    def view_box(self) -> tuple[float, float]: ...
    def connectors(self) -> list[Connector]: ...
    def anchor(
        self,
        index: int,
        position: Sequence[float],
        half_size: Sequence[float],
    ) -> tuple[float, float]: ...
    def aspect_half_size(
        self,
        *,
        width: float | None = None,
        height: float | None = None,
    ) -> tuple[float, float]: ...

def symbol_id_for(kind: EquipmentKind) -> str | None: ...
def symbol_ids() -> list[str]: ...
def find_symbol(symbol_id: str) -> Symbol | None: ...

VIEW_CLASS_IDENTIFIER: str
