from __future__ import annotations

class LoadPoint:
    def __init__(self, variable: str, value: float) -> None: ...
    def variable(self) -> str: ...
    def value(self) -> float: ...

class LoadProfile:
    def __init__(self, points: list[LoadPoint]) -> None: ...
    def points(self) -> list[LoadPoint]: ...
    def is_empty(self) -> bool: ...

class DesignLimit:
    def __init__(self, variable: str, max_value: float) -> None: ...
    def variable(self) -> str: ...
    def max_value(self) -> float: ...

class SafetyFactor:
    def __init__(self, value: float) -> None: ...
    def value(self) -> float: ...

class AcceptanceCriterion:
    def __init__(self, metric: str, max_value: float) -> None: ...
    def metric(self) -> str: ...
    def max_value(self) -> float: ...

class MeasuredOutcome:
    def __init__(self, metric: str, value: float) -> None: ...
    def metric(self) -> str: ...
    def value(self) -> float: ...

class StressTestState:
    Planned: StressTestState
    Completed: StressTestState

class StressTest:
    @staticmethod
    def plan(
        id: str,
        load_profile: LoadProfile,
        safety_factor: SafetyFactor,
        *,
        design_limits: list[DesignLimit],
        acceptance_criteria: list[AcceptanceCriterion],
    ) -> StressTest: ...
    def id(self) -> str: ...
    def state(self) -> StressTestState: ...
    def load_profile(self) -> LoadProfile: ...
    def safety_factor(self) -> SafetyFactor: ...
    def design_limits(self) -> list[DesignLimit]: ...
    def acceptance_criteria(self) -> list[AcceptanceCriterion]: ...
    def evaluate(self, outcomes: list[MeasuredOutcome]) -> bool: ...
