from __future__ import annotations

from .kernel import Quality, UnitOfMeasure

ARCHETYPE_PROCESS_VARIABLE: str
ARCHETYPE_TAG_METADATA: str
ARCHETYPE_PID_PIPE: str
ARCHETYPE_PID_SYMBOL: str
COMPONENT_QUALITY: str

class ProcessVariableSample:
    def __init__(self, value: float, quality: Quality) -> None: ...
    def value(self) -> float: ...
    def quality(self) -> Quality: ...

class TagMetadata:
    def __init__(self, unit: UnitOfMeasure, range_low: float, range_high: float) -> None: ...
    def unit_symbol(self) -> str: ...
    def range_low(self) -> float: ...
    def range_high(self) -> float: ...
    def alarm_low(self) -> float | None: ...
    def alarm_high(self) -> float | None: ...

def field(archetype: str, field_name: str) -> str: ...
